/*
 * EXT_INT_Designer.h
 *
 * Created: 15/01/2020 01:44:01
 *  Author: Native_programmer
 */ 


#ifndef EXT_INT_DESIGNER_H_
#define EXT_INT_DESIGNER_H_

#include "Data_Types.h"
#include "EXT_INT_PreLConfig.h"

typedef uinteg8_t EXT_INT_ERROR_t;
 
#define EXT_INT0_ENABLE()                EXT_INT_ENABLE_INT0_REG|=EXT_INT0_ENABLE_BITS 
#define EXT_INT1_ENABLE()                EXT_INT_ENABLE_INT1_REG|=EXT_INT1_ENABLE_BITS
#define EXT_INT2_ENABLE()                EXT_INT_ENABLE_INT2_REG|=EXT_INT2_ENABLE_BITS
#define EXT_INT0_EVENT_RISING_EDGE()     SET_VAlUE_IN_POSTION_FROM_tO(0,1,EXT_INT_EVENT_INT0_REG,EXT_INT0_EVENT_RISING_EDGE_BITS)
#define EXT_INT0_EVENT_FALLING_EDGE()    SET_VAlUE_IN_POSTION_FROM_tO(0,1,EXT_INT_EVENT_INT0_REG,EXT_INT0_EVENT_FALLING_EDGE_BITS)
#define EXT_INT1_EVENT_RISING_EDGE()     SET_VAlUE_IN_POSTION_FROM_tO(2,3,EXT_INT_EVENT_INT1_REG,EXT_INT1_EVENT_RISING_EDGE_BITS)
#define EXT_INT1_EVENT_FALLING_EDGE()    SET_VAlUE_IN_POSTION_FROM_tO(2,3,EXT_INT_EVENT_INT1_REG,EXT_INT1_EVENT_FALLING_EDGE_BITS)
#define EXT_INT2_EVENT_RISING_EDGE()     SET_BIT(EXT_INT_EVENT_INT2_REG,6);
#define EXT_INT2_EVENT_FALLING_EDGE()    CLR_BIT(EXT_INT_EVENT_INT2_REG,6);
#endif /* EXT_INT_DESIGNER_H_ */